### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by dm82m** [neiser/wemportal-scripts#1]
hey @neiser ,

we are also working on several approaches to automate the wemportal.com - see here: https://github.com/ioBroker/AdapterRequests/issues/218

A few questions from my side:

1. How fast is it to access the portal via Selenium?
2. Is it possible to run this on a Raspberry with Debian an no user interface in headless mode?
3. Are there any further plans also accessing specific settings like enabling/disabling the water heating?

Thanks for all your efforts!

Best,
Dirk

**Comment by neiser** [comment]
Hi @dm82m, let's continue the discussion in ioBroker/AdapterRequests#218
